spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://DOSTH-AUTH
          predicates:
            - Path=/auth/**
          filters:
          - StripPrefix=1