server:
  port: 8082

spring:
  application:
    name: dosth-gateway
  profiles:
    include: routers, jwt
   
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://locahost:8081/eureka/